# Generated by Django 4.1.3 on 2022-12-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_user_transaction_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
            ],
        ),
    ]
